{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aerostack.fullname" . }}-frontend
  labels:
    {{- include "aerostack.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aerostack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}

