{{- if .Values.serviceAccounts.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aerostack.serviceAccountName" . }}
  labels:
    {{- include "aerostack.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.automountServiceAccountToken }}
{{- end }}

